import 'package:flutter/material.dart';

class CategoryIcons {
  static const byKey = <String, IconData>{
    'restaurant': Icons.restaurant,
    'rice_bowl': Icons.rice_bowl,
    'fastfood': Icons.fastfood,
    'local_pizza': Icons.local_pizza,
    'cake': Icons.cake,
    'icecream': Icons.icecream,
    'bakery_dining': Icons.bakery_dining,
    'apple': Icons.apple,
    'banana': Icons.eco,
    'beef': Icons.kebab_dining,
    'candy': Icons.cake,
    'carrot': Icons.eco,
    'cherry': Icons.circle,
    'citrus': Icons.circle,
    'cookie': Icons.cookie,
    'cooking_pot': Icons.soup_kitchen,
    'cup_soda': Icons.local_drink,
    'donut': Icons.donut_large,
    'drumstick': Icons.restaurant,
    'egg': Icons.egg,
    'fish': Icons.set_meal,
    'flame': Icons.local_fire_department,
    'glass_water': Icons.water_drop,
    'glasses': Icons.wine_bar,
    'grape': Icons.grass,
    'ham': Icons.lunch_dining,
    'leaf': Icons.eco,
    'martini': Icons.local_bar,
    'milk': Icons.local_drink,
    'nut': Icons.scatter_plot,
    'package_open': Icons.inventory_2,
    'popcorn': Icons.local_dining,
    'salad': Icons.lunch_dining,
    'sandwich': Icons.lunch_dining,
    'wheat': Icons.grass,
    'wine': Icons.wine_bar,
    'indian_thali': Icons.restaurant,
    'tandoor': Icons.soup_kitchen,
    'curry_pot': Icons.soup_kitchen,
    'spice': Icons.local_fire_department,
    'lentils': Icons.grain,
    'coriander': Icons.eco,
    'masala': Icons.soup_kitchen,
    'roti': Icons.bakery_dining,
    'idli': Icons.rice_bowl,
    'chai': Icons.local_cafe,
  };

  static IconData resolve(String? key) => byKey[key] ?? Icons.restaurant;
}
